name: GunGun Deployment

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GUNGUN_HOST }}
          username: ${{ secrets.GUNGUN_USERNAME }}
          password: ${{ secrets.GUNGUN_PASSWORD }}
          port: 22
          script: |
            cd /home/gungun-backend

            echo "📥 Pull latest code..."
            git fetch origin
            git checkout production
            git pull origin production

            echo "📦 Installing dependencies..."
            npm install

            echo "🚀 Starting server with PM2..."
            pm2 startOrReload ecosystem.config.js --env production

            echo "✅ Deployment complete."
